import { randomUUID } from 'node:crypto';
import type { JobConfig, JobFn, JobID, TimeUnit, Weekday } from './types.js';
import {
  addSeconds,
  addMinutes,
  addHours,
  addDays,
  addWeeks,
  nextWeekday,
  setTime,
  randomBetween,
} from './parser.js';

/**
 * Represents a single scheduled job
 *
 * Created by `ScheduleBuilder.do()` and registered with a `Scheduler`.
 * You typically don't instantiate this class directly.
 *
 * @example
 * ```ts
 * const job = schedule.every(10).minutes.do(async (signal) => {
 *   const res = await fetch(url, { signal });
 * });
 * job.cancel(); // Cancel the job (sends AbortSignal if running)
 * ```
 */
export class Job {
  /** Unique job identifier (generated by `crypto.randomUUID()`) */
  readonly id: JobID;

  /** Tags attached to this job */
  readonly tags: string[];

  /** Last execution time. `null` if never run */
  lastRun: Date | null = null;

  /** Next scheduled execution time */
  nextRun: Date;

  /** Number of times this job has been executed */
  runCount = 0;

  /** Whether this job has been cancelled */
  cancelled = false;

  private readonly fn: JobFn;
  private readonly interval: number;
  private readonly intervalMax: number | null;
  private readonly unit: TimeUnit;
  private readonly atTime: string | null;
  private readonly weekday: Weekday | null;
  private readonly maxTimes: number | null;
  private readonly until: Date | null;
  private readonly skipIfRunning: boolean;

  private running = false;
  private abortController: AbortController | null = null;

  /** Error callback (set by Scheduler) */
  onError: ((job: Job, err: unknown) => void) | null = null;

  constructor(config: JobConfig) {
    this.id = randomUUID();
    this.fn = config.fn;
    this.interval = config.interval;
    this.intervalMax = config.intervalMax;
    this.unit = config.unit;
    this.atTime = config.atTime;
    this.weekday = config.weekday;
    this.tags = [...config.tags];
    this.maxTimes = config.maxTimes;
    this.until = config.until;
    this.skipIfRunning = config.skipIfRunning;
    this.nextRun = this.calcNextRun();
  }

  /**
   * Calculate the next run time
   * @param from - Base time. Defaults to now
   * @returns Next execution Date
   */
  calcNextRun(from: Date = new Date()): Date {
    const interval = this.intervalMax
      ? randomBetween(this.interval, this.intervalMax)
      : this.interval;

    switch (this.unit) {
      case 'seconds':
        return addSeconds(from, interval);
      case 'minutes':
        return addMinutes(from, interval);
      case 'hours':
        return addHours(from, interval);
      case 'days': {
        const base = addDays(from, interval);
        if (this.atTime) return setTime(base, this.atTime);
        return base;
      }
      case 'weeks': {
        if (this.weekday) {
          const next = nextWeekday(from, this.weekday, interval);
          if (this.atTime) return setTime(next, this.atTime);
          return next;
        }
        const base = addWeeks(from, interval);
        if (this.atTime) return setTime(base, this.atTime);
        return base;
      }
    }
  }

  /**
   * Execute the job
   *
   * Skips execution if cancelled, expired, max times reached,
   * or if `skipIfRunning` is enabled and a previous run is still in progress.
   *
   * @returns `true` on success, `false` on skip/error/cancel
   */
  async run(): Promise<boolean> {
    if (this.cancelled) return false;

    if (this.until && new Date() > this.until) {
      this.cancel();
      return false;
    }

    if (this.maxTimes !== null && this.runCount >= this.maxTimes) {
      this.cancel();
      return false;
    }

    if (this.skipIfRunning && this.running) return false;

    this.abortController = new AbortController();
    this.running = true;
    this.lastRun = new Date();
    this.runCount++;

    try {
      await this.fn(this.abortController.signal);
      return true;
    } catch (err) {
      // AbortError is a normal cancellation, not an error
      if (err instanceof Error && err.name === 'AbortError') return false;
      if (this.onError) {
        this.onError(this, err);
      } else {
        console.error(`[yotei] Job execution error: id=${this.id}`, err);
      }
      return false;
    } finally {
      this.running = false;
      if (!this.cancelled) {
        this.nextRun = this.calcNextRun();
      }
    }
  }

  /**
   * Cancel the job
   *
   * If running, sends an `AbortSignal` to interrupt operations like `fetch`.
   * After cancellation, the job will not run on subsequent `runPending()` calls
   * and will be removed from the Scheduler.
   */
  cancel(): void {
    this.cancelled = true;
    this.abortController?.abort();
  }

  /** Whether the job is currently running */
  get isRunning(): boolean {
    return this.running;
  }

  /**
   * Check whether the job can run at the given time
   *
   * Used by Scheduler for pre-run checks before emitting events.
   * Evaluates the same conditions as `run()` (cancelled, deadline, max times,
   * skipIfRunning) but has no side effects.
   */
  canRun(now: Date = new Date()): boolean {
    if (this.cancelled) return false;
    if (this.until && now > this.until) return false;
    if (this.maxTimes !== null && this.runCount >= this.maxTimes) return false;
    if (this.skipIfRunning && this.running) return false;
    return true;
  }
}
